name: Locust Check

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
        -name: TEST
          run: ls -la
      # - name: Setup locust from git directly
      #   run: pip install git+https://github.com/simiotics/locust.git@main
      # - name: Run locust
      #   run: |
      #     locust origin/main HEAD --github "https://github.com/${GITHUB_REPOSITORY}" --format html  \
      #     | tee result.html
      # - name: Upload locust results to Bugout
      #   env:
      #     BUGOUT_SECRET: ${{ secrets.BUGOUT_SECRET }}
      #   run: |
      #     curl -k -X POST https://69d1084159fc.ngrok.io/github/summary \
      #       -H "Content-Type: multipart/form-data" \
      #       -F "summary=$(base64 result.html)" \
      #       -F "summary_format=html" \
      #       -F "target_hash=$(git log --format=oneline -2 | tail -n+2 | awk '{print $1}')" \
      #       -F "bugout_secret=$BUGOUT_SECRET"
