name: Locust summary

on: [ pull_request_target ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: PR head repo
        id: head_repo_name
        run: |
          HEAD_REPO_NAME=$(jq -r '.pull_request.head.repo.full_name' "$GITHUB_EVENT_PATH")
          echo "PR head repo: $HEAD_REPO_NAME"
          echo "::set-output name=repo::$HEAD_REPO_NAME"
      - name: Checkout git repo
        uses: actions/checkout@v2
        with:
          repository: ${{ steps.head_repo_name.outputs.repo }}
          fetch-depth: 0
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install bugout-locust
      - name: Generate Locust summary
        run: |
          INITIAL_REF="$INPUT_INITIAL_REF"
          TERMINAL_REF="$INPUT_TERMINAL_REF"
          FORMAT="${INPUT_FORMAT:-json}"
          REPO="/github/workspace/$REPO_SUBDIR"
          if [ -z "$INITIAL_REF" ] then INITIAL_REF=$(locust.github initial) fi 
          if [ -z "$TERMINAL_REF" ] then TERMINAL_REF=$(locust.github terminal) fi
          REPO_URL=$(locust.github repo)

          locust --format "$FORMAT" -r "$REPO" "$INITIAL_REF" "$TERMINAL_REF" --github "${REPO_URL}" | tee /locust.summary
