name: Locust Check

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Check GitHub environment variables
        run: echo "Action ID - ${GITHUB_ACTION}, Run ID - ${GITHUB_RUN_ID}, Workflow - ${GITHUB_WORKFLOW}, Repository - ${GITHUB_REPOSITORY}, SHA - ${GITHUB_SHA}, Ref - ${GITHUB_REF}"
      - name: Check git log
        run: git log --pretty
