name: Locust summary

on: [ pull_request_target ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: PR head repo
        id: head_repo_name
        run: |
          HEAD_REPO_NAME=$(jq -r '.pull_request.head.repo.full_name' "$GITHUB_EVENT_PATH")
          echo "PR head repo: $HEAD_REPO_NAME"
          echo "::set-output name=repo::$HEAD_REPO_NAME"
      - name: Checkout git repo
        uses: actions/checkout@v2
        with:
          repository: ${{ steps.head_repo_name.outputs.repo }}
          fetch-depth: 0
      - name: Generate Locust summary
        uses: simiotics/locust-action@v0.1.5
        id: locust
        with:
          format: json
      - name: Upload locust results to Bugout
        env:
          BUGOUT_SECRET: ${{ secrets.BUGOUT_SECRET }}
        run: |
          curl -k -X POST https://8df26850a151.ngrok.io/github/summary \
            -H "Content-Type: multipart/form-data" \
            -F "summary=${{ steps.locust.outputs.summary }}'" \
            -F "summary_format=json" \
            -F "terminal_hash=$(git log --format=oneline -2 | tail -n+2 | awk '{print $1}')" \
            -F "bugout_secret=$BUGOUT_SECRET"
      - name: Check local json
        run: cat /home/runner/work/_temp/_github_workflow/event.json | jq '.pull_request._links.comments.href'
