name: Locust summary

on: [ pull_request_target ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: PR head repo
        id: head_repo_name
        run: |
          HEAD_REPO_NAME=$(jq -r '.pull_request.head.repo.full_name' "$GITHUB_EVENT_PATH")
          echo "PR head repo: $HEAD_REPO_NAME"
          echo "::set-output name=repo::$HEAD_REPO_NAME"
      - name: Checkout git repo
        uses: actions/checkout@v2
        with:
          repository: ${{ steps.head_repo_name.outputs.repo }}
          fetch-depth: 0
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          pwd_path=$(pwd)
          git clone https://github.com/kompotkot/locust.git /tmp/locust
          cd /tmp/locust
          git checkout origin/push-ci-helper
          python -m pip install --upgrade pip setuptools
          pip install -e .
          cd $pwd_path
      - name: Cat GITHUB_EVENT_PATH
        run: |
          cat $GITHUB_EVENT_PATH
      - name: Run locust
        run: |
          locust.github send
